INSERT DATA {
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/oa#Annotation> }
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09> <http://purl.org/dc/terms/source> "https://hypothes.is/api/annotations/URh_jq4kQfibaXggbegwyQ" }
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09> <http://purl.org/dc/terms/title> "http://data.perseus.org/people/smith:aetolus-1#this identifies Aetolus as snap:SonOf in urn:cts:pdlrefwk:viaf88890045.003.perseus-eng1:E.endymion_1" }
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09> <http://www.w3.org/ns/oa#annotatedAt> "2015-02-20T02:11:02.328046+00:00"^^<http://www.w3.org/2001/XMLSchema#dateTimeStamp> }
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09> <http://www.w3.org/ns/oa#annotatedBy> <http://data.perseus.org/sosol/users/John%20Shepard,%20Joseph%20Caplan,%20Luke%20O'Connor> }
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09> <http://www.w3.org/ns/oa#hasBody> <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09> }
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09> <http://www.w3.org/ns/oa#hasTarget> <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09#target-1> }
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09> <http://www.w3.org/ns/oa#motivatedBy> <http://www.w3.org/ns/oa#identifying> }
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09> <http://www.w3.org/ns/oa#serializedBy> <https://hypothes.is> }
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09#target-1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/oa#SpecificResource> }
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09#target-1> <http://www.w3.org/ns/oa#hasSelector> <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09#target-1-sel-1> }
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09#target-1> <http://www.w3.org/ns/oa#hasSource> <urn:cts:pdlrefwk:viaf88890045.003.perseus-eng1:E.endymion_1> }
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09#target-1-sel-1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.w3.org/ns/oa#TextQuoteSelector> }
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09#target-1-sel-1> <http://www.w3.org/ns/oa#exact> "Aetolus" }
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09#target-1-sel-1> <http://www.w3.org/ns/oa#prefix> "rippe, Neis, or Iphianassa; and" }
GRAPH <http://data.perseus.org/graphs/persons> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09#target-1-sel-1> <http://www.w3.org/ns/oa#suffix> ", Paeon, Epeius. Eurydice, and N" }
GRAPH <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09> { <http://data.perseus.org/people/smith:endymion-1#this> <snap:has-bond> <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09#bond-1> }
GRAPH <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09#bond-1> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <snap:SonOf> }
GRAPH <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09> { <http://data.perseus.org/collections/urn:cite:perseus:pdljann.9a89ff50c8400132f58f0ada42b1fd09#bond-1> <snap:bond-with> <http://data.perseus.org/people/smith:aetolus-1#this> }
}
